OLED_ENABLE = yes
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
CONVERT_TO=liatris
CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes
SEND_STRING_ENABLE = yes
AUTOCORRECT_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes
WPM_ENABLE = yes
